name: Deploy VitePress site to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Clean dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Build with VitePress
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          publish_branch: gh-pages
